@isTest 
private class dummyTestClass{
    static testMethod void testMethod1(){
        ClassForTestCoverage testCoverage = new ClassForTestCoverage();
        testCoverage.myDummy1();
        testCoverage.myDummy2();
        testCoverage.myDummy3();
        testCoverage.myDummy4();
        testCoverage.myDummy5();
        testCoverage.myDummy6();
        testCoverage.myDummy7();
        testCoverage.myDummy8();
        testCoverage.myDummy9();
        testCoverage.myDummy10();
        testCoverage.myDummy11();
        testCoverage.myDummy12();
        testCoverage.myDummy13();
        testCoverage.myDummy14();
        testCoverage.myDummy15();  
        testCoverage.myDummy16();
        testCoverage.myDummy17();
        testCoverage.myDummy18();
        testCoverage.myDummy19();
        testCoverage.myDummy20();
        testCoverage.myDummy21();
        testCoverage.myDummy22();
        testCoverage.myDummy23();
        testCoverage.myDummy24();
        testCoverage.myDummy25();
        testCoverage.myDummy26();
        testCoverage.myDummy27();
        testCoverage.myDummy28();
        testCoverage.myDummy29();
        testCoverage.myDummy30();
    }
}